version: '3.1'

services:
  api:
    container_name: recipe-server
    build: 
      context: . 
      dockerfile: ./docker/development/api/Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "3003:3000"
    command: ['npm', 'run', 'dev']
    depends_on:
      - db
  db:
    container_name: recipe-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: recipe
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql